import 'package:flutter/material.dart';
import 'package:flutterapp/pdca4app/generatedpronehipextensionwidget/generated/GeneratedExercise5Widget4.dart';
import 'package:flutterapp/pdca4app/generatedpronehipextensionwidget/generated/GeneratedStabilizethepelvisreducestrainonthebackcanhelpimproveyo.dart';
import 'package:flutterapp/pdca4app/generatedpronehipextensionwidget/generated/GeneratedComponent5Widget12.dart';
import 'package:flutterapp/pdca4app/generatedpronehipextensionwidget/generated/GeneratedProneHipExtensionWidget1.dart';
import 'package:flutterapp/pdca4app/generatedpronehipextensionwidget/generated/GeneratedGroup10Widget13.dart';
import 'package:flutterapp/pdca4app/generatedpronehipextensionwidget/generated/GeneratedGroup2Widget15.dart';
import 'package:flutterapp/pdca4app/generatedpronehipextensionwidget/generated/GeneratedAdvantagesWidget1.dart';
import 'package:flutterapp/pdca4app/generatedpronehipextensionwidget/generated/GeneratedLieonyourstomachonthefloorwithyourlegsstraightYoucanlie.dart';

/* Frame Prone Hip extension
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProneHipextensionWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 250, 250, 250),
                ),
              ),
              Positioned(
                left: -94.0,
                top: -100.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 296.0,
                child: GeneratedGroup2Widget15(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 47.0,
                child: GeneratedGroup10Widget13(),
              ),
              Positioned(
                left: 0.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 51.0,
                child: GeneratedComponent5Widget12(),
              ),
              Positioned(
                left: 27.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 110.0,
                child:
                    GeneratedLieonyourstomachonthefloorwithyourlegsstraightYoucanlie(),
              ),
              Positioned(
                left: 28.0,
                top: 358.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 56.0,
                child:
                    GeneratedStabilizethepelvisreducestrainonthebackcanhelpimproveyo(),
              ),
              Positioned(
                left: 28.0,
                top: 179.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 25.0,
                child: GeneratedProneHipExtensionWidget1(),
              ),
              Positioned(
                left: 28.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 25.0,
                child: GeneratedAdvantagesWidget1(),
              ),
              Positioned(
                left: 43.0,
                top: 435.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 300.0,
                child: GeneratedExercise5Widget4(),
              )
            ]),
      ),
    ));
  }
}
