import 'package:flutter/material.dart';
import 'package:flutterapp/pdca4app/generatede1widget/generated/GeneratedGroup10Widget4.dart';
import 'package:flutterapp/pdca4app/generatede1widget/generated/GeneratedComponent5Widget3.dart';
import 'package:flutterapp/pdca4app/generatede1widget/generated/GeneratedGroup2Widget6.dart';
import 'package:flutterapp/pdca4app/generatede1widget/generated/GeneratedWhatsAppVideo20221117at1111Widget12.dart';

/* Frame e1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedE1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 250, 250, 250),
                ),
              ),
              Positioned(
                left: -94.0,
                top: -100.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 296.0,
                child: GeneratedGroup2Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 47.0,
                child: GeneratedGroup10Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 51.0,
                child: GeneratedComponent5Widget3(),
              ),
              Positioned(
                left: 47.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 300.0,
                child: GeneratedWhatsAppVideo20221117at1111Widget12(),
              )
            ]),
      ),
    ));
  }
}
