import 'package:flutter/material.dart';
import 'package:flutterapp/pdca4app/generatedexercisewidget1/generated/GeneratedGroup26Widget.dart';
import 'package:flutterapp/pdca4app/generatedexercisewidget1/generated/GeneratedAnteriorTiltWidget.dart';
import 'package:flutterapp/pdca4app/generatedexercisewidget1/generated/GeneratedGroup10Widget1.dart';
import 'package:flutterapp/pdca4app/generatedexercisewidget1/generated/GeneratedPostureDetectionCorrectionApplicationWidget3.dart';
import 'package:flutterapp/pdca4app/generatedexercisewidget1/generated/GeneratedComponent5Widget.dart';
import 'package:flutterapp/pdca4app/generatedexercisewidget1/generated/GeneratedGroup2Widget3.dart';
import 'package:flutterapp/pdca4app/generatedexercisewidget1/generated/GeneratedGroup27Widget.dart';
import 'package:flutterapp/pdca4app/generatedexercisewidget1/generated/GeneratedGroup25Widget.dart';
import 'package:flutterapp/pdca4app/generatedexercisewidget1/generated/GeneratedGroup24Widget.dart';

/* Frame Exercise
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedExerciseWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 250, 250, 250),
                ),
              ),
              Positioned(
                left: -94.0,
                top: -100.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 296.0,
                child: GeneratedGroup2Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 47.0,
                child: GeneratedGroup10Widget1(),
              ),
              Positioned(
                left: 10.0,
                top: 142.0,
                right: null,
                bottom: null,
                width: 364.0,
                height: 61.0,
                child: GeneratedPostureDetectionCorrectionApplicationWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 51.0,
                child: GeneratedComponent5Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 41.0,
                child: GeneratedAnteriorTiltWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 261.0,
                right: null,
                bottom: null,
                width: 363.0,
                height: 123.0,
                child: GeneratedGroup24Widget(),
              ),
              Positioned(
                left: 13.0,
                top: 399.0,
                right: null,
                bottom: null,
                width: 363.0,
                height: 123.0,
                child: GeneratedGroup25Widget(),
              ),
              Positioned(
                left: 15.0,
                top: 537.0,
                right: null,
                bottom: null,
                width: 363.0,
                height: 123.0,
                child: GeneratedGroup26Widget(),
              ),
              Positioned(
                left: 13.0,
                top: 675.0,
                right: null,
                bottom: null,
                width: 363.0,
                height: 123.0,
                child: GeneratedGroup27Widget(),
              )
            ]),
      ),
    ));
  }
}
