import 'package:flutter/material.dart';
import 'package:flutterapp/pdca4app/generatedpronehipextensionwidget1/generated/GeneratedProneTswithBackExtensionExerciseWidget1.dart';
import 'package:flutterapp/pdca4app/generatedpronehipextensionwidget1/generated/GeneratedGroup2Widget16.dart';
import 'package:flutterapp/pdca4app/generatedpronehipextensionwidget1/generated/GeneratedGroup10Widget14.dart';
import 'package:flutterapp/pdca4app/generatedpronehipextensionwidget1/generated/GeneratedExercise5Widget5.dart';
import 'package:flutterapp/pdca4app/generatedpronehipextensionwidget1/generated/GeneratedComponent5Widget13.dart';
import 'package:flutterapp/pdca4app/generatedpronehipextensionwidget1/generated/GeneratedStartbylyingfacedownwithyourlegstogetherandyourarmsouta.dart';

/* Frame Prone Hip extension
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProneHipextensionWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 250, 250, 250),
                ),
              ),
              Positioned(
                left: -94.0,
                top: -100.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 296.0,
                child: GeneratedGroup2Widget16(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 47.0,
                child: GeneratedGroup10Widget14(),
              ),
              Positioned(
                left: 0.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 51.0,
                child: GeneratedComponent5Widget13(),
              ),
              Positioned(
                left: 28.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 291.0,
                child:
                    GeneratedStartbylyingfacedownwithyourlegstogetherandyourarmsouta(),
              ),
              Positioned(
                left: 28.0,
                top: 169.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 25.0,
                child: GeneratedProneTswithBackExtensionExerciseWidget1(),
              ),
              Positioned(
                left: 47.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 300.0,
                child: GeneratedExercise5Widget5(),
              )
            ]),
      ),
    ));
  }
}
