import 'package:flutter/material.dart';
import 'package:flutterapp/pdca4app/generatede1widget5/generated/GeneratedComponent5Widget8.dart';
import 'package:flutterapp/pdca4app/generatede1widget5/generated/GeneratedGroup10Widget9.dart';
import 'package:flutterapp/pdca4app/generatede1widget5/generated/GeneratedExemplaryEnlightenedConysize_restricted1Widget2.dart';
import 'package:flutterapp/pdca4app/generatede1widget5/generated/GeneratedGroup2Widget11.dart';

/* Frame e1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedE1Widget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 250, 250, 250),
                ),
              ),
              Positioned(
                left: -94.0,
                top: -100.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 296.0,
                child: GeneratedGroup2Widget11(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 47.0,
                child: GeneratedGroup10Widget9(),
              ),
              Positioned(
                left: 0.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 51.0,
                child: GeneratedComponent5Widget8(),
              ),
              Positioned(
                left: 47.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 300.0,
                child:
                    GeneratedExemplaryEnlightenedConysize_restricted1Widget2(),
              )
            ]),
      ),
    ));
  }
}
