import 'package:flutter/material.dart';
import 'package:flutterapp/pdca4app/generatedcameraaccesswidget/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/pdca4app/generatedcameraaccesswidget/generated/GeneratedGroup2Widget1.dart';
import 'package:flutterapp/pdca4app/generatedcameraaccesswidget/generated/GeneratedUndraw_mobile_photos_psm511Widget.dart';
import 'package:flutterapp/pdca4app/generatedcameraaccesswidget/generated/GeneratedGroup11Widget1.dart';
import 'package:flutterapp/pdca4app/generatedcameraaccesswidget/generated/GeneratedPostureDetectionCorrectionApplicationWidget1.dart';
import 'package:flutterapp/pdca4app/generatedcameraaccesswidget/generated/GeneratedOrTaptoUploadfromGalleryWidget.dart';
import 'package:flutterapp/pdca4app/generatedcameraaccesswidget/generated/GeneratedTaptotakeaphotoWidget.dart';

/* Frame Camera access
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCameraaccessWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 250, 250, 250),
                ),
              ),
              Positioned(
                left: 22.0,
                top: 197.0,
                right: null,
                bottom: null,
                width: 348.0,
                height: 451.0,
                child: GeneratedGroup7Widget(),
              ),
              Positioned(
                left: -94.0,
                top: -100.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 296.0,
                child: GeneratedGroup2Widget1(),
              ),
              Positioned(
                left: 19.0,
                top: 688.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 75.0,
                child: GeneratedTaptotakeaphotoWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 103.0,
                right: null,
                bottom: null,
                width: 364.0,
                height: 61.0,
                child: GeneratedPostureDetectionCorrectionApplicationWidget1(),
              ),
              Positioned(
                left: 48.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 217.0,
                child: GeneratedUndraw_mobile_photos_psm511Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 47.0,
                child: GeneratedGroup11Widget1(),
              ),
              Positioned(
                left: 80.0,
                top: 774.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 38.0,
                child: GeneratedOrTaptoUploadfromGalleryWidget(),
              )
            ]),
      ),
    ));
  }
}
