import 'package:flutter/material.dart';

/* Text Boost flexibility, Reduce knee and back pain, Strengthen your core, including your abs, Whittle your waistline – including your obliques, Improve balance, Relieve back pain, Improve posture
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBoostflexibilityReducekneeandbackpainStrengthenyourcore
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Align(
      alignment: Alignment.centerLeft,
      child: Text(
        '''Boost flexibility, Reduce knee and back pain, Strengthen your core, including your abs, Whittle your waistline – including your obliques, Improve balance, Relieve back pain, Improve posture''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.left,
        style: TextStyle(
          height: 1.5,
          fontSize: 12.0,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w600,
          color: Color.fromARGB(255, 49, 49, 49),

          /* letterSpacing: 0.0, */
        ),
      ),
    ));
  }
}
