import 'package:flutter/material.dart';
import 'package:flutterapp/pdca4app/generatedslashframewidget/generated/GeneratedPostureDetectionCorrectionApplicationWidget6.dart';
import 'package:flutterapp/pdca4app/generatedslashframewidget/generated/GeneratedPDCAWidget16.dart';
import 'package:flutterapp/pdca4app/generatedslashframewidget/generated/GeneratedGroup2Widget19.dart';
import 'package:flutterapp/pdca4app/generatedslashframewidget/generated/GeneratedUndraw_personal_trainer_re_cnua1Widget.dart';
import 'package:flutterapp/pdca4app/generatedslashframewidget/generated/GeneratedGroup13Widget.dart';
import 'package:flutterapp/pdca4app/generatedslashframewidget/generated/GeneratedGroup1Widget.dart';

/* Frame slash frame
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSlashframeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 29.0,
                top: 231.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 282.0,
                child: GeneratedUndraw_personal_trainer_re_cnua1Widget(),
              ),
              Positioned(
                left: 105.0,
                top: 531.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 76.0,
                child: GeneratedPDCAWidget16(),
              ),
              Positioned(
                left: 15.0,
                top: 599.0,
                right: null,
                bottom: null,
                width: 364.0,
                height: 61.0,
                child: GeneratedPostureDetectionCorrectionApplicationWidget6(),
              ),
              Positioned(
                left: -94.0,
                top: -100.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 296.0,
                child: GeneratedGroup2Widget19(),
              ),
              Positioned(
                left: 19.0,
                top: 688.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 75.0,
                child: GeneratedGroup1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 47.0,
                child: GeneratedGroup13Widget(),
              )
            ]),
      ),
    ));
  }
}
