import 'package:flutter/material.dart';
import 'package:flutterapp/pdca4app/generatedanalyzepartwidget1/generated/GeneratedRectangle34Widget.dart';
import 'package:flutterapp/pdca4app/generatedanalyzepartwidget1/generated/GeneratedPostureDescriptionKyphosisSwaybackBodyAlignmentWidget.dart';
import 'package:flutterapp/pdca4app/generatedanalyzepartwidget1/generated/GeneratedSg1Widget1.dart';
import 'package:flutterapp/pdca4app/generatedanalyzepartwidget1/generated/GeneratedGroup36Widget.dart';
import 'package:flutterapp/pdca4app/generatedanalyzepartwidget1/generated/GeneratedGroup11Widget4.dart';
import 'package:flutterapp/pdca4app/generatedanalyzepartwidget1/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/pdca4app/generatedanalyzepartwidget1/generated/GeneratedGroup33Widget.dart';
import 'package:flutterapp/pdca4app/generatedanalyzepartwidget1/generated/GeneratedPercentages67717696Widget.dart';

/* Frame analyze part
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAnalyzepartWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 223, 223, 223),
                ),
              ),
              Positioned(
                left: 22.0,
                top: 472.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 194.0,
                child: GeneratedRectangle34Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 47.0,
                child: GeneratedGroup11Widget4(),
              ),
              Positioned(
                left: 79.0,
                top: 118.0,
                right: null,
                bottom: null,
                width: 235.0,
                height: 324.0,
                child: GeneratedSg1Widget1(),
              ),
              Positioned(
                left: 175.5,
                top: 436.1407470703125,
                right: null,
                bottom: null,
                width: 300.2815246582031,
                height: 4.0,
                child: GeneratedLine2Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 504.0,
                right: null,
                bottom: null,
                width: 174.0,
                height: 187.0,
                child:
                    GeneratedPostureDescriptionKyphosisSwaybackBodyAlignmentWidget(),
              ),
              Positioned(
                left: 227.0,
                top: 504.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 161.0,
                child: GeneratedPercentages67717696Widget(),
              ),
              Positioned(
                left: 31.0,
                top: 694.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 40.0,
                child: GeneratedGroup33Widget(),
              ),
              Positioned(
                left: 216.0,
                top: 694.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 40.0,
                child: GeneratedGroup36Widget(),
              )
            ]),
      ),
    ));
  }
}
