import 'package:flutter/material.dart';

/* Frame Gallery
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGalleryWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedAnalyzepartWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 393.0,
          height: 852.0,
          child: ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 250, 250, 250),
            ),
          ),
        ),
      ),
    ));
  }
}
