import 'package:flutter/material.dart';
import 'package:flutterapp/pdca4app/generatedframe1widget/generated/GeneratedGroup18Widget.dart';
import 'package:flutterapp/pdca4app/generatedframe1widget/generated/GeneratedUserID23342313Widget1.dart';
import 'package:flutterapp/pdca4app/generatedframe1widget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/pdca4app/generatedframe1widget/generated/GeneratedUserID23342313Widget.dart';

/* Frame Frame 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: Container(
        width: 348.0,
        height: 485.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(40.0),
          border: Border.all(
            width: 8.0,
            color: Color.fromARGB(255, 77, 176, 215),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(40.0),
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: 43.0,
                top: 41.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 409.0,
                child: GeneratedGroup18Widget(),
              ),
              Positioned(
                left: 184.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 192.0,
                height: 3.0,
                child: GeneratedLine1Widget(),
              ),
              Positioned(
                left: 78.0,
                top: 171.0,
                right: null,
                bottom: null,
                width: 195.0,
                height: 26.0,
                child: GeneratedUserID23342313Widget(),
              ),
              Positioned(
                left: 78.0,
                top: 171.0,
                right: null,
                bottom: null,
                width: 195.0,
                height: 26.0,
                child: GeneratedUserID23342313Widget1(),
              )
            ]),
      ),
    ));
  }
}
