import 'package:flutter/material.dart';
import 'package:flutterapp/pdca4app/generatedgallerywidget3/generated/GeneratedCvcdc1Widget.dart';
import 'package:flutterapp/pdca4app/generatedgallerywidget3/generated/GeneratedGroup11Widget2.dart';
import 'package:flutterapp/pdca4app/generatedgallerywidget3/generated/GeneratedRectangle37Widget.dart';
import 'package:flutterapp/pdca4app/generatedgallerywidget3/generated/GeneratedRectangle38Widget.dart';
import 'package:flutterapp/pdca4app/generatedgallerywidget3/generated/GeneratedTapWidget.dart';

/* Frame Gallery
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGalleryWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 250, 250, 250),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 47.0,
                child: GeneratedGroup11Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 798.5313110351562,
                child: GeneratedCvcdc1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 143.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 113.0,
                child: GeneratedTapWidget(),
              ),
              Positioned(
                left: 106.0,
                top: 143.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 113.0,
                child: GeneratedRectangle37Widget(),
              ),
              Positioned(
                left: 212.0,
                top: 143.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 113.0,
                child: GeneratedRectangle38Widget(),
              )
            ]),
      ),
    ));
  }
}
