import 'package:flutter/material.dart';
import 'package:flutterapp/pdca4app/generateddreportwidget/generated/GeneratedGroup37Widget2.dart';
import 'package:flutterapp/pdca4app/generateddreportwidget/generated/GeneratedGroup38Widget.dart';
import 'package:flutterapp/pdca4app/generateddreportwidget/generated/GeneratedDateOfAnalysis1262022Widget.dart';
import 'package:flutterapp/pdca4app/generateddreportwidget/generated/GeneratedRectangle35Widget.dart';
import 'package:flutterapp/pdca4app/generateddreportwidget/generated/GeneratedCompletePotureOverviewWithHighProbabilitywehavedetected.dart';
import 'package:flutterapp/pdca4app/generateddreportwidget/generated/GeneratedReportID234533Widget.dart';
import 'package:flutterapp/pdca4app/generateddreportwidget/generated/GeneratedPreferredExerciseWidget.dart';
import 'package:flutterapp/pdca4app/generateddreportwidget/generated/GeneratedGroup11Widget5.dart';
import 'package:flutterapp/pdca4app/generateddreportwidget/generated/GeneratedGroup39Widget.dart';
import 'package:flutterapp/pdca4app/generateddreportwidget/generated/GeneratedPOSTUREREPORTWidget.dart';

/* Frame Dreport
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDreportWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 223, 223, 223),
                ),
              ),
              Positioned(
                left: 32.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 758.0,
                child: GeneratedRectangle35Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 47.0,
                child: GeneratedGroup11Widget5(),
              ),
              Positioned(
                left: 57.0,
                top: 93.0,
                right: null,
                bottom: null,
                width: 279.0,
                height: 47.0,
                child: GeneratedPOSTUREREPORTWidget(),
              ),
              Positioned(
                left: 57.0,
                top: 192.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 188.0,
                child:
                    GeneratedCompletePotureOverviewWithHighProbabilitywehavedetected(),
              ),
              Positioned(
                left: 57.0,
                top: 138.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 20.0,
                child: GeneratedDateOfAnalysis1262022Widget(),
              ),
              Positioned(
                left: 57.0,
                top: 165.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 20.0,
                child: GeneratedReportID234533Widget(),
              ),
              Positioned(
                left: 52.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 21.0,
                child: GeneratedPreferredExerciseWidget(),
              ),
              Positioned(
                left: 48.0,
                top: 415.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 312.0,
                child: GeneratedGroup38Widget(),
              ),
              Positioned(
                left: 48.0,
                top: 415.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 312.0,
                child: GeneratedGroup39Widget(),
              ),
              Positioned(
                left: 124.0,
                top: 757.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 40.0,
                child: GeneratedGroup37Widget2(),
              )
            ]),
      ),
    ));
  }
}
