import 'package:flutter/material.dart';
import 'package:flutterapp/pdca4app/generatedbridgeingexercisewidget/generated/GeneratedGroup2Widget5.dart';
import 'package:flutterapp/pdca4app/generatedbridgeingexercisewidget/generated/GeneratedExercise5Widget3.dart';
import 'package:flutterapp/pdca4app/generatedbridgeingexercisewidget/generated/GeneratedBridgeexerciseWidget.dart';
import 'package:flutterapp/pdca4app/generatedbridgeingexercisewidget/generated/GeneratedAdvantagesWidget.dart';
import 'package:flutterapp/pdca4app/generatedbridgeingexercisewidget/generated/GeneratedDothebridgetostrengthenyourcoremusclesLieonyourbackwith.dart';
import 'package:flutterapp/pdca4app/generatedbridgeingexercisewidget/generated/GeneratedGroup10Widget3.dart';
import 'package:flutterapp/pdca4app/generatedbridgeingexercisewidget/generated/GeneratedComponent5Widget2.dart';

/* Frame Bridgeing exercise
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBridgeingexerciseWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 250, 250, 250),
                ),
              ),
              Positioned(
                left: -94.0,
                top: -100.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 296.0,
                child: GeneratedGroup2Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 47.0,
                child: GeneratedGroup10Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 51.0,
                child: GeneratedComponent5Widget2(),
              ),
              Positioned(
                left: 28.0,
                top: 191.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 110.0,
                child:
                    GeneratedDothebridgetostrengthenyourcoremusclesLieonyourbackwith(),
              ),
              Positioned(
                left: 28.0,
                top: 162.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 25.0,
                child: GeneratedBridgeexerciseWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 324.0,
                right: null,
                bottom: null,
                width: 252.0,
                height: 28.0,
                child: GeneratedAdvantagesWidget(),
              ),
              Positioned(
                left: 47.0,
                top: 449.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 300.0,
                child: GeneratedExercise5Widget3(),
              )
            ]),
      ),
    ));
  }
}
