import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/pdca4app/generatede1widget4/generated/GeneratedGroup10Widget8.dart';
import 'package:flutterapp/pdca4app/generatede1widget4/generated/GeneratedComponent5Widget7.dart';
import 'package:flutterapp/pdca4app/generatede1widget4/generated/GeneratedExercise7Widget.dart';
import 'package:flutterapp/pdca4app/generatede1widget4/generated/GeneratedGroup2Widget10.dart';

/* Frame e1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedE1Widget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 250, 250, 250),
                ),
              ),
              Positioned(
                left: -94.0,
                top: -100.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 296.0,
                child: GeneratedGroup2Widget10(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 47.0,
                child: GeneratedGroup10Widget8(),
              ),
              Positioned(
                left: 0.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 51.0,
                child: GeneratedComponent5Widget7(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7633587786259542;

                  final double height =
                      constraints.maxHeight * 0.352112676056338;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.11959287531806616,
                        y: constraints.maxHeight * 0.323943661971831,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedExercise7Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
