import 'package:flutter/material.dart';
import 'package:flutterapp/pdca4app/generateddonkeykickposturewidget/generated/GeneratedExercise1Widget1.dart';
import 'package:flutterapp/pdca4app/generateddonkeykickposturewidget/generated/GeneratedBoostsBalanceandMobilityPromoteshealthypostureEffective.dart';
import 'package:flutterapp/pdca4app/generateddonkeykickposturewidget/generated/GeneratedDonkeykickPostureWidget1.dart';
import 'package:flutterapp/pdca4app/generateddonkeykickposturewidget/generated/GeneratedDonkeykickPostureWidget.dart';
import 'package:flutterapp/pdca4app/generateddonkeykickposturewidget/generated/GeneratedComponent5Widget1.dart';
import 'package:flutterapp/pdca4app/generateddonkeykickposturewidget/generated/GeneratedGroup10Widget2.dart';
import 'package:flutterapp/pdca4app/generateddonkeykickposturewidget/generated/GeneratedStartbylyingfaceuponyourmatkneesbentwithyourfeetonthefl.dart';
import 'package:flutterapp/pdca4app/generateddonkeykickposturewidget/generated/GeneratedGroup2Widget4.dart';

/* Frame Donkey Kick Posture
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDonkeyKickPostureWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 250, 250, 250),
                ),
              ),
              Positioned(
                left: -94.0,
                top: -100.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 296.0,
                child: GeneratedGroup2Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 47.0,
                child: GeneratedGroup10Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 51.0,
                child: GeneratedComponent5Widget1(),
              ),
              Positioned(
                left: 43.0,
                top: 442.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 300.0,
                child: GeneratedExercise1Widget1(),
              ),
              Positioned(
                left: 28.0,
                top: 207.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 110.0,
                child:
                    GeneratedStartbylyingfaceuponyourmatkneesbentwithyourfeetonthefl(),
              ),
              Positioned(
                left: 28.0,
                top: 362.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 56.0,
                child:
                    GeneratedBoostsBalanceandMobilityPromoteshealthypostureEffective(),
              ),
              Positioned(
                left: 28.0,
                top: 178.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 25.0,
                child: GeneratedDonkeykickPostureWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 333.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 25.0,
                child: GeneratedDonkeykickPostureWidget1(),
              )
            ]),
      ),
    ));
  }
}
