import 'package:flutter/material.dart';
import 'package:flutterapp/pdca4app/generateddreportwidget1/generated/GeneratedRectangle35Widget1.dart';
import 'package:flutterapp/pdca4app/generateddreportwidget1/generated/GeneratedPOSTUREREPORTWidget1.dart';
import 'package:flutterapp/pdca4app/generateddreportwidget1/generated/GeneratedDateOfAnalysis1262022Widget1.dart';
import 'package:flutterapp/pdca4app/generateddreportwidget1/generated/GeneratedGroup37Widget5.dart';
import 'package:flutterapp/pdca4app/generateddreportwidget1/generated/GeneratedGroup39Widget1.dart';
import 'package:flutterapp/pdca4app/generateddreportwidget1/generated/GeneratedPreferredExerciseWidget1.dart';
import 'package:flutterapp/pdca4app/generateddreportwidget1/generated/GeneratedGroup38Widget1.dart';
import 'package:flutterapp/pdca4app/generateddreportwidget1/generated/GeneratedReportID234534Widget.dart';
import 'package:flutterapp/pdca4app/generateddreportwidget1/generated/GeneratedCompletePotureOverviewWithHighProbabilitywehavedetected1.dart';
import 'package:flutterapp/pdca4app/generateddreportwidget1/generated/GeneratedGroup11Widget6.dart';

/* Frame Dreport
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDreportWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 223, 223, 223),
                ),
              ),
              Positioned(
                left: 32.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 758.0,
                child: GeneratedRectangle35Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 47.0,
                child: GeneratedGroup11Widget6(),
              ),
              Positioned(
                left: 57.0,
                top: 93.0,
                right: null,
                bottom: null,
                width: 279.0,
                height: 47.0,
                child: GeneratedPOSTUREREPORTWidget1(),
              ),
              Positioned(
                left: 57.0,
                top: 192.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 188.0,
                child:
                    GeneratedCompletePotureOverviewWithHighProbabilitywehavedetected1(),
              ),
              Positioned(
                left: 57.0,
                top: 138.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 20.0,
                child: GeneratedDateOfAnalysis1262022Widget1(),
              ),
              Positioned(
                left: 57.0,
                top: 165.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 20.0,
                child: GeneratedReportID234534Widget(),
              ),
              Positioned(
                left: 52.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 21.0,
                child: GeneratedPreferredExerciseWidget1(),
              ),
              Positioned(
                left: 48.0,
                top: 415.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 312.0,
                child: GeneratedGroup38Widget1(),
              ),
              Positioned(
                left: 48.0,
                top: 415.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 312.0,
                child: GeneratedGroup39Widget1(),
              ),
              Positioned(
                left: 124.0,
                top: 757.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 40.0,
                child: GeneratedGroup37Widget5(),
              )
            ]),
      ),
    ));
  }
}
