import 'package:flutter/material.dart';
import 'package:flutterapp/pdca4app/generatedprofilewidget/generated/GeneratedPostureDetectionCorrectionApplicationWidget.dart';
import 'package:flutterapp/pdca4app/generatedprofilewidget/generated/GeneratedGroup11Widget.dart';
import 'package:flutterapp/pdca4app/generatedprofilewidget/generated/GeneratedProfilesWidget.dart';
import 'package:flutterapp/pdca4app/generatedprofilewidget/generated/GeneratedGroup2Widget.dart';

/* Component Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(63, 0, 0, 0),
            offset: Offset(0.0, 4.0),
            blurRadius: 4.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 393.0,
          height: 852.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              clipBehavior: Clip.none,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: -94.0,
                  top: -100.0,
                  right: null,
                  bottom: null,
                  width: 265.0,
                  height: 296.0,
                  child: GeneratedGroup2Widget(),
                ),
                Positioned(
                  left: 10.0,
                  top: 103.0,
                  right: null,
                  bottom: null,
                  width: 364.0,
                  height: 61.0,
                  child: GeneratedPostureDetectionCorrectionApplicationWidget(),
                ),
                Positioned(
                  left: 37.0,
                  top: 173.0,
                  right: null,
                  bottom: null,
                  width: 320.0,
                  height: 628.0,
                  child: GeneratedProfilesWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 393.0,
                  height: 47.0,
                  child: GeneratedGroup11Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
