import 'package:flutter/material.dart';
import 'package:flutterapp/pdca4app/generatede1widget8/generated/GeneratedGroup2Widget14.dart';
import 'package:flutterapp/pdca4app/generatede1widget8/generated/GeneratedGroup10Widget12.dart';
import 'package:flutterapp/pdca4app/generatede1widget8/generated/GeneratedC9b78b82320d77d80260f704373fe3ed2Widget.dart';
import 'package:flutterapp/pdca4app/generatede1widget8/generated/GeneratedComponent5Widget11.dart';

/* Frame e1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedE1Widget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 250, 250, 250),
                ),
              ),
              Positioned(
                left: -94.0,
                top: -100.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 296.0,
                child: GeneratedGroup2Widget14(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 47.0,
                child: GeneratedGroup10Widget12(),
              ),
              Positioned(
                left: 0.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 51.0,
                child: GeneratedComponent5Widget11(),
              ),
              Positioned(
                left: 47.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 300.0,
                child: GeneratedC9b78b82320d77d80260f704373fe3ed2Widget(),
              )
            ]),
      ),
    ));
  }
}
