import 'package:flutter/material.dart';
import 'package:flutterapp/pdca4app/generatedreportwidget2/generated/GeneratedComponent3Widget.dart';
import 'package:flutterapp/pdca4app/generatedreportwidget2/generated/GeneratedGroup29Widget.dart';
import 'package:flutterapp/pdca4app/generatedreportwidget2/generated/GeneratedGroup30Widget.dart';
import 'package:flutterapp/pdca4app/generatedreportwidget2/generated/GeneratedGroup19Widget.dart';
import 'package:flutterapp/pdca4app/generatedreportwidget2/generated/GeneratedGroup2Widget17.dart';
import 'package:flutterapp/pdca4app/generatedreportwidget2/generated/GeneratedGroup10Widget15.dart';
import 'package:flutterapp/pdca4app/generatedreportwidget2/generated/GeneratedPostureDetectionCorrectionApplicationWidget4.dart';

/* Frame Report
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedReportWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -94.0,
                top: -100.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 296.0,
                child: GeneratedGroup2Widget17(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 47.0,
                child: GeneratedGroup10Widget15(),
              ),
              Positioned(
                left: 10.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 364.0,
                height: 61.0,
                child: GeneratedPostureDetectionCorrectionApplicationWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 51.0,
                child: GeneratedGroup19Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 185.0,
                right: null,
                bottom: null,
                width: 338.3744201660156,
                height: 236.0,
                child: GeneratedGroup29Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 505.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 303.0,
                child: GeneratedComponent3Widget(),
              ),
              Positioned(
                left: 60.0,
                top: 421.0,
                right: null,
                bottom: null,
                width: 273.0,
                height: 80.0,
                child: GeneratedGroup30Widget(),
              )
            ]),
      ),
    ));
  }
}
