import 'package:flutter/material.dart';
import 'package:flutterapp/pdca4app/generatedregisterwidget/generated/GeneratedQuickstartSkipNowWidget.dart';
import 'package:flutterapp/pdca4app/generatedregisterwidget/generated/GeneratedGroup12Widget.dart';
import 'package:flutterapp/pdca4app/generatedregisterwidget/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/pdca4app/generatedregisterwidget/generated/GeneratedHeightWidget1.dart';
import 'package:flutterapp/pdca4app/generatedregisterwidget/generated/GeneratedGroup2Widget18.dart';
import 'package:flutterapp/pdca4app/generatedregisterwidget/generated/GeneratedPostureDetectionCorrectionApplicationWidget5.dart';
import 'package:flutterapp/pdca4app/generatedregisterwidget/generated/GeneratedNameWidget1.dart';
import 'package:flutterapp/pdca4app/generatedregisterwidget/generated/GeneratedAlreadyhaveaprofileSelectaProfileWidget.dart';
import 'package:flutterapp/pdca4app/generatedregisterwidget/generated/GeneratedButtoncreateprofileWidget.dart';
import 'package:flutterapp/pdca4app/generatedregisterwidget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/pdca4app/generatedregisterwidget/generated/GeneratedAgeWidget1.dart';
import 'package:flutterapp/pdca4app/generatedregisterwidget/generated/GeneratedUndraw_mobile_login_re_9ntv11Widget.dart';

/* Frame register
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegisterWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 224.0,
                top: 776.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 18.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: -94.0,
                top: -100.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 296.0,
                child: GeneratedGroup2Widget18(),
              ),
              Positioned(
                left: 20.0,
                top: 672.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 75.0,
                child: GeneratedButtoncreateprofileWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 103.0,
                right: null,
                bottom: null,
                width: 364.0,
                height: 61.0,
                child: GeneratedPostureDetectionCorrectionApplicationWidget5(),
              ),
              Positioned(
                left: 19.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 45.0,
                child: GeneratedNameWidget1(),
              ),
              Positioned(
                left: 19.0,
                top: 470.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 45.0,
                child: GeneratedAgeWidget1(),
              ),
              Positioned(
                left: 19.0,
                top: 535.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 45.0,
                child: GeneratedGroup4Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 45.0,
                child: GeneratedHeightWidget1(),
              ),
              Positioned(
                left: -24.0,
                top: 762.0,
                right: null,
                bottom: null,
                width: 443.0,
                height: 36.0,
                child: GeneratedAlreadyhaveaprofileSelectaProfileWidget(),
              ),
              Positioned(
                left: 83.0,
                top: 799.0,
                right: null,
                bottom: null,
                width: 230.0,
                height: 31.0,
                child: GeneratedQuickstartSkipNowWidget(),
              ),
              Positioned(
                left: 96.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 202.0,
                height: 158.0,
                child: GeneratedUndraw_mobile_login_re_9ntv11Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 47.0,
                child: GeneratedGroup12Widget(),
              )
            ]),
      ),
    ));
  }
}
